/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// Add virtual folder dto.
    /// </summary>
    [DataContract]
    public partial class AddVirtualFolderDto :  IEquatable<AddVirtualFolderDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddVirtualFolderDto" /> class.
        /// </summary>
        /// <param name="libraryOptions">Gets or sets library options..</param>
        public AddVirtualFolderDto(LibraryOptions libraryOptions = default(LibraryOptions))
        {
            this.LibraryOptions = libraryOptions;
            this.LibraryOptions = libraryOptions;
        }

        /// <summary>
        /// Gets or sets library options.
        /// </summary>
        /// <value>Gets or sets library options.</value>
        [DataMember(Name="LibraryOptions", EmitDefaultValue=true)]
        public LibraryOptions LibraryOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddVirtualFolderDto {\n");
            sb.Append("  LibraryOptions: ").Append(LibraryOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddVirtualFolderDto);
        }

        /// <summary>
        /// Returns true if AddVirtualFolderDto instances are equal
        /// </summary>
        /// <param name="input">Instance of AddVirtualFolderDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddVirtualFolderDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LibraryOptions == input.LibraryOptions ||
                    (this.LibraryOptions != null &&
                    this.LibraryOptions.Equals(input.LibraryOptions))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LibraryOptions != null)
                    hashCode = hashCode * 59 + this.LibraryOptions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
