/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// Defines ChannelItemSortField
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ChannelItemSortField
    {
        /// <summary>
        /// Enum Name for value: Name
        /// </summary>
        [EnumMember(Value = "Name")]
        Name = 1,

        /// <summary>
        /// Enum CommunityRating for value: CommunityRating
        /// </summary>
        [EnumMember(Value = "CommunityRating")]
        CommunityRating = 2,

        /// <summary>
        /// Enum PremiereDate for value: PremiereDate
        /// </summary>
        [EnumMember(Value = "PremiereDate")]
        PremiereDate = 3,

        /// <summary>
        /// Enum DateCreated for value: DateCreated
        /// </summary>
        [EnumMember(Value = "DateCreated")]
        DateCreated = 4,

        /// <summary>
        /// Enum Runtime for value: Runtime
        /// </summary>
        [EnumMember(Value = "Runtime")]
        Runtime = 5,

        /// <summary>
        /// Enum PlayCount for value: PlayCount
        /// </summary>
        [EnumMember(Value = "PlayCount")]
        PlayCount = 6,

        /// <summary>
        /// Enum CommunityPlayCount for value: CommunityPlayCount
        /// </summary>
        [EnumMember(Value = "CommunityPlayCount")]
        CommunityPlayCount = 7

    }

}
