/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// Defines ForgotPasswordAction
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ForgotPasswordAction
    {
        /// <summary>
        /// Enum ContactAdmin for value: ContactAdmin
        /// </summary>
        [EnumMember(Value = "ContactAdmin")]
        ContactAdmin = 1,

        /// <summary>
        /// Enum PinCode for value: PinCode
        /// </summary>
        [EnumMember(Value = "PinCode")]
        PinCode = 2,

        /// <summary>
        /// Enum InNetworkRequired for value: InNetworkRequired
        /// </summary>
        [EnumMember(Value = "InNetworkRequired")]
        InNetworkRequired = 3

    }

}
