/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// GeneralCommand
    /// </summary>
    [DataContract]
    public partial class GeneralCommand :  IEquatable<GeneralCommand>, IValidatableObject
    {
        /// <summary>
        /// This exists simply to identify a set of known commands.
        /// </summary>
        /// <value>This exists simply to identify a set of known commands.</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public GeneralCommandType? Name { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GeneralCommand" /> class.
        /// </summary>
        /// <param name="name">This exists simply to identify a set of known commands..</param>
        /// <param name="controllingUserId">controllingUserId.</param>
        /// <param name="arguments">arguments.</param>
        public GeneralCommand(GeneralCommandType? name = default(GeneralCommandType?), Guid controllingUserId = default(Guid), Dictionary<string, string> arguments = default(Dictionary<string, string>))
        {
            this.Arguments = arguments;
            this.Name = name;
            this.ControllingUserId = controllingUserId;
            this.Arguments = arguments;
        }


        /// <summary>
        /// Gets or Sets ControllingUserId
        /// </summary>
        [DataMember(Name="ControllingUserId", EmitDefaultValue=false)]
        public Guid ControllingUserId { get; set; }

        /// <summary>
        /// Gets or Sets Arguments
        /// </summary>
        [DataMember(Name="Arguments", EmitDefaultValue=true)]
        public Dictionary<string, string> Arguments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GeneralCommand {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ControllingUserId: ").Append(ControllingUserId).Append("\n");
            sb.Append("  Arguments: ").Append(Arguments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GeneralCommand);
        }

        /// <summary>
        /// Returns true if GeneralCommand instances are equal
        /// </summary>
        /// <param name="input">Instance of GeneralCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GeneralCommand input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ControllingUserId == input.ControllingUserId ||
                    (this.ControllingUserId != null &&
                    this.ControllingUserId.Equals(input.ControllingUserId))
                ) && 
                (
                    this.Arguments == input.Arguments ||
                    this.Arguments != null &&
                    input.Arguments != null &&
                    this.Arguments.SequenceEqual(input.Arguments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ControllingUserId != null)
                    hashCode = hashCode * 59 + this.ControllingUserId.GetHashCode();
                if (this.Arguments != null)
                    hashCode = hashCode * 59 + this.Arguments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
