/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// This exists simply to identify a set of known commands.
    /// </summary>
    /// <value>This exists simply to identify a set of known commands.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum GeneralCommandType
    {
        /// <summary>
        /// Enum MoveUp for value: MoveUp
        /// </summary>
        [EnumMember(Value = "MoveUp")]
        MoveUp = 1,

        /// <summary>
        /// Enum MoveDown for value: MoveDown
        /// </summary>
        [EnumMember(Value = "MoveDown")]
        MoveDown = 2,

        /// <summary>
        /// Enum MoveLeft for value: MoveLeft
        /// </summary>
        [EnumMember(Value = "MoveLeft")]
        MoveLeft = 3,

        /// <summary>
        /// Enum MoveRight for value: MoveRight
        /// </summary>
        [EnumMember(Value = "MoveRight")]
        MoveRight = 4,

        /// <summary>
        /// Enum PageUp for value: PageUp
        /// </summary>
        [EnumMember(Value = "PageUp")]
        PageUp = 5,

        /// <summary>
        /// Enum PageDown for value: PageDown
        /// </summary>
        [EnumMember(Value = "PageDown")]
        PageDown = 6,

        /// <summary>
        /// Enum PreviousLetter for value: PreviousLetter
        /// </summary>
        [EnumMember(Value = "PreviousLetter")]
        PreviousLetter = 7,

        /// <summary>
        /// Enum NextLetter for value: NextLetter
        /// </summary>
        [EnumMember(Value = "NextLetter")]
        NextLetter = 8,

        /// <summary>
        /// Enum ToggleOsd for value: ToggleOsd
        /// </summary>
        [EnumMember(Value = "ToggleOsd")]
        ToggleOsd = 9,

        /// <summary>
        /// Enum ToggleContextMenu for value: ToggleContextMenu
        /// </summary>
        [EnumMember(Value = "ToggleContextMenu")]
        ToggleContextMenu = 10,

        /// <summary>
        /// Enum Select for value: Select
        /// </summary>
        [EnumMember(Value = "Select")]
        Select = 11,

        /// <summary>
        /// Enum Back for value: Back
        /// </summary>
        [EnumMember(Value = "Back")]
        Back = 12,

        /// <summary>
        /// Enum TakeScreenshot for value: TakeScreenshot
        /// </summary>
        [EnumMember(Value = "TakeScreenshot")]
        TakeScreenshot = 13,

        /// <summary>
        /// Enum SendKey for value: SendKey
        /// </summary>
        [EnumMember(Value = "SendKey")]
        SendKey = 14,

        /// <summary>
        /// Enum SendString for value: SendString
        /// </summary>
        [EnumMember(Value = "SendString")]
        SendString = 15,

        /// <summary>
        /// Enum GoHome for value: GoHome
        /// </summary>
        [EnumMember(Value = "GoHome")]
        GoHome = 16,

        /// <summary>
        /// Enum GoToSettings for value: GoToSettings
        /// </summary>
        [EnumMember(Value = "GoToSettings")]
        GoToSettings = 17,

        /// <summary>
        /// Enum VolumeUp for value: VolumeUp
        /// </summary>
        [EnumMember(Value = "VolumeUp")]
        VolumeUp = 18,

        /// <summary>
        /// Enum VolumeDown for value: VolumeDown
        /// </summary>
        [EnumMember(Value = "VolumeDown")]
        VolumeDown = 19,

        /// <summary>
        /// Enum Mute for value: Mute
        /// </summary>
        [EnumMember(Value = "Mute")]
        Mute = 20,

        /// <summary>
        /// Enum Unmute for value: Unmute
        /// </summary>
        [EnumMember(Value = "Unmute")]
        Unmute = 21,

        /// <summary>
        /// Enum ToggleMute for value: ToggleMute
        /// </summary>
        [EnumMember(Value = "ToggleMute")]
        ToggleMute = 22,

        /// <summary>
        /// Enum SetVolume for value: SetVolume
        /// </summary>
        [EnumMember(Value = "SetVolume")]
        SetVolume = 23,

        /// <summary>
        /// Enum SetAudioStreamIndex for value: SetAudioStreamIndex
        /// </summary>
        [EnumMember(Value = "SetAudioStreamIndex")]
        SetAudioStreamIndex = 24,

        /// <summary>
        /// Enum SetSubtitleStreamIndex for value: SetSubtitleStreamIndex
        /// </summary>
        [EnumMember(Value = "SetSubtitleStreamIndex")]
        SetSubtitleStreamIndex = 25,

        /// <summary>
        /// Enum ToggleFullscreen for value: ToggleFullscreen
        /// </summary>
        [EnumMember(Value = "ToggleFullscreen")]
        ToggleFullscreen = 26,

        /// <summary>
        /// Enum DisplayContent for value: DisplayContent
        /// </summary>
        [EnumMember(Value = "DisplayContent")]
        DisplayContent = 27,

        /// <summary>
        /// Enum GoToSearch for value: GoToSearch
        /// </summary>
        [EnumMember(Value = "GoToSearch")]
        GoToSearch = 28,

        /// <summary>
        /// Enum DisplayMessage for value: DisplayMessage
        /// </summary>
        [EnumMember(Value = "DisplayMessage")]
        DisplayMessage = 29,

        /// <summary>
        /// Enum SetRepeatMode for value: SetRepeatMode
        /// </summary>
        [EnumMember(Value = "SetRepeatMode")]
        SetRepeatMode = 30,

        /// <summary>
        /// Enum ChannelUp for value: ChannelUp
        /// </summary>
        [EnumMember(Value = "ChannelUp")]
        ChannelUp = 31,

        /// <summary>
        /// Enum ChannelDown for value: ChannelDown
        /// </summary>
        [EnumMember(Value = "ChannelDown")]
        ChannelDown = 32,

        /// <summary>
        /// Enum Guide for value: Guide
        /// </summary>
        [EnumMember(Value = "Guide")]
        Guide = 33,

        /// <summary>
        /// Enum ToggleStats for value: ToggleStats
        /// </summary>
        [EnumMember(Value = "ToggleStats")]
        ToggleStats = 34,

        /// <summary>
        /// Enum PlayMediaSource for value: PlayMediaSource
        /// </summary>
        [EnumMember(Value = "PlayMediaSource")]
        PlayMediaSource = 35,

        /// <summary>
        /// Enum PlayTrailers for value: PlayTrailers
        /// </summary>
        [EnumMember(Value = "PlayTrailers")]
        PlayTrailers = 36,

        /// <summary>
        /// Enum SetShuffleQueue for value: SetShuffleQueue
        /// </summary>
        [EnumMember(Value = "SetShuffleQueue")]
        SetShuffleQueue = 37,

        /// <summary>
        /// Enum PlayState for value: PlayState
        /// </summary>
        [EnumMember(Value = "PlayState")]
        PlayState = 38,

        /// <summary>
        /// Enum PlayNext for value: PlayNext
        /// </summary>
        [EnumMember(Value = "PlayNext")]
        PlayNext = 39,

        /// <summary>
        /// Enum ToggleOsdMenu for value: ToggleOsdMenu
        /// </summary>
        [EnumMember(Value = "ToggleOsdMenu")]
        ToggleOsdMenu = 40,

        /// <summary>
        /// Enum Play for value: Play
        /// </summary>
        [EnumMember(Value = "Play")]
        Play = 41

    }

}
