/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// ListingsProviderInfo
    /// </summary>
    [DataContract]
    public partial class ListingsProviderInfo :  IEquatable<ListingsProviderInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingsProviderInfo" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="type">type.</param>
        /// <param name="username">username.</param>
        /// <param name="password">password.</param>
        /// <param name="listingsId">listingsId.</param>
        /// <param name="zipCode">zipCode.</param>
        /// <param name="country">country.</param>
        /// <param name="path">path.</param>
        /// <param name="enabledTuners">enabledTuners.</param>
        /// <param name="enableAllTuners">enableAllTuners.</param>
        /// <param name="newsCategories">newsCategories.</param>
        /// <param name="sportsCategories">sportsCategories.</param>
        /// <param name="kidsCategories">kidsCategories.</param>
        /// <param name="movieCategories">movieCategories.</param>
        /// <param name="channelMappings">channelMappings.</param>
        /// <param name="moviePrefix">moviePrefix.</param>
        /// <param name="preferredLanguage">preferredLanguage.</param>
        /// <param name="userAgent">userAgent.</param>
        public ListingsProviderInfo(string id = default(string), string type = default(string), string username = default(string), string password = default(string), string listingsId = default(string), string zipCode = default(string), string country = default(string), string path = default(string), List<string> enabledTuners = default(List<string>), bool enableAllTuners = default(bool), List<string> newsCategories = default(List<string>), List<string> sportsCategories = default(List<string>), List<string> kidsCategories = default(List<string>), List<string> movieCategories = default(List<string>), List<NameValuePair> channelMappings = default(List<NameValuePair>), string moviePrefix = default(string), string preferredLanguage = default(string), string userAgent = default(string))
        {
            this.Id = id;
            this.Type = type;
            this.Username = username;
            this.Password = password;
            this.ListingsId = listingsId;
            this.ZipCode = zipCode;
            this.Country = country;
            this.Path = path;
            this.EnabledTuners = enabledTuners;
            this.NewsCategories = newsCategories;
            this.SportsCategories = sportsCategories;
            this.KidsCategories = kidsCategories;
            this.MovieCategories = movieCategories;
            this.ChannelMappings = channelMappings;
            this.MoviePrefix = moviePrefix;
            this.PreferredLanguage = preferredLanguage;
            this.UserAgent = userAgent;
            this.Id = id;
            this.Type = type;
            this.Username = username;
            this.Password = password;
            this.ListingsId = listingsId;
            this.ZipCode = zipCode;
            this.Country = country;
            this.Path = path;
            this.EnabledTuners = enabledTuners;
            this.EnableAllTuners = enableAllTuners;
            this.NewsCategories = newsCategories;
            this.SportsCategories = sportsCategories;
            this.KidsCategories = kidsCategories;
            this.MovieCategories = movieCategories;
            this.ChannelMappings = channelMappings;
            this.MoviePrefix = moviePrefix;
            this.PreferredLanguage = preferredLanguage;
            this.UserAgent = userAgent;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="Type", EmitDefaultValue=true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name="Username", EmitDefaultValue=true)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="Password", EmitDefaultValue=true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets ListingsId
        /// </summary>
        [DataMember(Name="ListingsId", EmitDefaultValue=true)]
        public string ListingsId { get; set; }

        /// <summary>
        /// Gets or Sets ZipCode
        /// </summary>
        [DataMember(Name="ZipCode", EmitDefaultValue=true)]
        public string ZipCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="Country", EmitDefaultValue=true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name="Path", EmitDefaultValue=true)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets EnabledTuners
        /// </summary>
        [DataMember(Name="EnabledTuners", EmitDefaultValue=true)]
        public List<string> EnabledTuners { get; set; }

        /// <summary>
        /// Gets or Sets EnableAllTuners
        /// </summary>
        [DataMember(Name="EnableAllTuners", EmitDefaultValue=false)]
        public bool EnableAllTuners { get; set; }

        /// <summary>
        /// Gets or Sets NewsCategories
        /// </summary>
        [DataMember(Name="NewsCategories", EmitDefaultValue=true)]
        public List<string> NewsCategories { get; set; }

        /// <summary>
        /// Gets or Sets SportsCategories
        /// </summary>
        [DataMember(Name="SportsCategories", EmitDefaultValue=true)]
        public List<string> SportsCategories { get; set; }

        /// <summary>
        /// Gets or Sets KidsCategories
        /// </summary>
        [DataMember(Name="KidsCategories", EmitDefaultValue=true)]
        public List<string> KidsCategories { get; set; }

        /// <summary>
        /// Gets or Sets MovieCategories
        /// </summary>
        [DataMember(Name="MovieCategories", EmitDefaultValue=true)]
        public List<string> MovieCategories { get; set; }

        /// <summary>
        /// Gets or Sets ChannelMappings
        /// </summary>
        [DataMember(Name="ChannelMappings", EmitDefaultValue=true)]
        public List<NameValuePair> ChannelMappings { get; set; }

        /// <summary>
        /// Gets or Sets MoviePrefix
        /// </summary>
        [DataMember(Name="MoviePrefix", EmitDefaultValue=true)]
        public string MoviePrefix { get; set; }

        /// <summary>
        /// Gets or Sets PreferredLanguage
        /// </summary>
        [DataMember(Name="PreferredLanguage", EmitDefaultValue=true)]
        public string PreferredLanguage { get; set; }

        /// <summary>
        /// Gets or Sets UserAgent
        /// </summary>
        [DataMember(Name="UserAgent", EmitDefaultValue=true)]
        public string UserAgent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListingsProviderInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  ListingsId: ").Append(ListingsId).Append("\n");
            sb.Append("  ZipCode: ").Append(ZipCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  EnabledTuners: ").Append(EnabledTuners).Append("\n");
            sb.Append("  EnableAllTuners: ").Append(EnableAllTuners).Append("\n");
            sb.Append("  NewsCategories: ").Append(NewsCategories).Append("\n");
            sb.Append("  SportsCategories: ").Append(SportsCategories).Append("\n");
            sb.Append("  KidsCategories: ").Append(KidsCategories).Append("\n");
            sb.Append("  MovieCategories: ").Append(MovieCategories).Append("\n");
            sb.Append("  ChannelMappings: ").Append(ChannelMappings).Append("\n");
            sb.Append("  MoviePrefix: ").Append(MoviePrefix).Append("\n");
            sb.Append("  PreferredLanguage: ").Append(PreferredLanguage).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListingsProviderInfo);
        }

        /// <summary>
        /// Returns true if ListingsProviderInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ListingsProviderInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListingsProviderInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                ) && 
                (
                    this.ListingsId == input.ListingsId ||
                    (this.ListingsId != null &&
                    this.ListingsId.Equals(input.ListingsId))
                ) && 
                (
                    this.ZipCode == input.ZipCode ||
                    (this.ZipCode != null &&
                    this.ZipCode.Equals(input.ZipCode))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.EnabledTuners == input.EnabledTuners ||
                    this.EnabledTuners != null &&
                    input.EnabledTuners != null &&
                    this.EnabledTuners.SequenceEqual(input.EnabledTuners)
                ) && 
                (
                    this.EnableAllTuners == input.EnableAllTuners ||
                    (this.EnableAllTuners != null &&
                    this.EnableAllTuners.Equals(input.EnableAllTuners))
                ) && 
                (
                    this.NewsCategories == input.NewsCategories ||
                    this.NewsCategories != null &&
                    input.NewsCategories != null &&
                    this.NewsCategories.SequenceEqual(input.NewsCategories)
                ) && 
                (
                    this.SportsCategories == input.SportsCategories ||
                    this.SportsCategories != null &&
                    input.SportsCategories != null &&
                    this.SportsCategories.SequenceEqual(input.SportsCategories)
                ) && 
                (
                    this.KidsCategories == input.KidsCategories ||
                    this.KidsCategories != null &&
                    input.KidsCategories != null &&
                    this.KidsCategories.SequenceEqual(input.KidsCategories)
                ) && 
                (
                    this.MovieCategories == input.MovieCategories ||
                    this.MovieCategories != null &&
                    input.MovieCategories != null &&
                    this.MovieCategories.SequenceEqual(input.MovieCategories)
                ) && 
                (
                    this.ChannelMappings == input.ChannelMappings ||
                    this.ChannelMappings != null &&
                    input.ChannelMappings != null &&
                    this.ChannelMappings.SequenceEqual(input.ChannelMappings)
                ) && 
                (
                    this.MoviePrefix == input.MoviePrefix ||
                    (this.MoviePrefix != null &&
                    this.MoviePrefix.Equals(input.MoviePrefix))
                ) && 
                (
                    this.PreferredLanguage == input.PreferredLanguage ||
                    (this.PreferredLanguage != null &&
                    this.PreferredLanguage.Equals(input.PreferredLanguage))
                ) && 
                (
                    this.UserAgent == input.UserAgent ||
                    (this.UserAgent != null &&
                    this.UserAgent.Equals(input.UserAgent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                if (this.ListingsId != null)
                    hashCode = hashCode * 59 + this.ListingsId.GetHashCode();
                if (this.ZipCode != null)
                    hashCode = hashCode * 59 + this.ZipCode.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.EnabledTuners != null)
                    hashCode = hashCode * 59 + this.EnabledTuners.GetHashCode();
                if (this.EnableAllTuners != null)
                    hashCode = hashCode * 59 + this.EnableAllTuners.GetHashCode();
                if (this.NewsCategories != null)
                    hashCode = hashCode * 59 + this.NewsCategories.GetHashCode();
                if (this.SportsCategories != null)
                    hashCode = hashCode * 59 + this.SportsCategories.GetHashCode();
                if (this.KidsCategories != null)
                    hashCode = hashCode * 59 + this.KidsCategories.GetHashCode();
                if (this.MovieCategories != null)
                    hashCode = hashCode * 59 + this.MovieCategories.GetHashCode();
                if (this.ChannelMappings != null)
                    hashCode = hashCode * 59 + this.ChannelMappings.GetHashCode();
                if (this.MoviePrefix != null)
                    hashCode = hashCode * 59 + this.MoviePrefix.GetHashCode();
                if (this.PreferredLanguage != null)
                    hashCode = hashCode * 59 + this.PreferredLanguage.GetHashCode();
                if (this.UserAgent != null)
                    hashCode = hashCode * 59 + this.UserAgent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
