/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// Media Encoder Path Dto.
    /// </summary>
    [DataContract]
    public partial class MediaEncoderPathDto :  IEquatable<MediaEncoderPathDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaEncoderPathDto" /> class.
        /// </summary>
        /// <param name="path">Gets or sets media encoder path..</param>
        /// <param name="pathType">Gets or sets media encoder path type..</param>
        public MediaEncoderPathDto(string path = default(string), string pathType = default(string))
        {
            this.Path = path;
            this.PathType = pathType;
            this.Path = path;
            this.PathType = pathType;
        }

        /// <summary>
        /// Gets or sets media encoder path.
        /// </summary>
        /// <value>Gets or sets media encoder path.</value>
        [DataMember(Name="Path", EmitDefaultValue=true)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or sets media encoder path type.
        /// </summary>
        /// <value>Gets or sets media encoder path type.</value>
        [DataMember(Name="PathType", EmitDefaultValue=true)]
        public string PathType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MediaEncoderPathDto {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  PathType: ").Append(PathType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MediaEncoderPathDto);
        }

        /// <summary>
        /// Returns true if MediaEncoderPathDto instances are equal
        /// </summary>
        /// <param name="input">Instance of MediaEncoderPathDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MediaEncoderPathDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.PathType == input.PathType ||
                    (this.PathType != null &&
                    this.PathType.Equals(input.PathType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.PathType != null)
                    hashCode = hashCode * 59 + this.PathType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
