/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Jellyfin.Api.Client.OpenAPIDateConverter;

namespace Jellyfin.Api.Model
{
    /// <summary>
    /// Class PlayRequestDto.
    /// </summary>
    [DataContract]
    public partial class PlayRequestDto :  IEquatable<PlayRequestDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayRequestDto" /> class.
        /// </summary>
        /// <param name="playingQueue">Gets or sets the playing queue..</param>
        /// <param name="playingItemPosition">Gets or sets the position of the playing item in the queue..</param>
        /// <param name="startPositionTicks">Gets or sets the start position ticks..</param>
        public PlayRequestDto(List<Guid> playingQueue = default(List<Guid>), int playingItemPosition = default(int), long startPositionTicks = default(long))
        {
            this.PlayingQueue = playingQueue;
            this.PlayingQueue = playingQueue;
            this.PlayingItemPosition = playingItemPosition;
            this.StartPositionTicks = startPositionTicks;
        }

        /// <summary>
        /// Gets or sets the playing queue.
        /// </summary>
        /// <value>Gets or sets the playing queue.</value>
        [DataMember(Name="PlayingQueue", EmitDefaultValue=true)]
        public List<Guid> PlayingQueue { get; set; }

        /// <summary>
        /// Gets or sets the position of the playing item in the queue.
        /// </summary>
        /// <value>Gets or sets the position of the playing item in the queue.</value>
        [DataMember(Name="PlayingItemPosition", EmitDefaultValue=false)]
        public int PlayingItemPosition { get; set; }

        /// <summary>
        /// Gets or sets the start position ticks.
        /// </summary>
        /// <value>Gets or sets the start position ticks.</value>
        [DataMember(Name="StartPositionTicks", EmitDefaultValue=false)]
        public long StartPositionTicks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlayRequestDto {\n");
            sb.Append("  PlayingQueue: ").Append(PlayingQueue).Append("\n");
            sb.Append("  PlayingItemPosition: ").Append(PlayingItemPosition).Append("\n");
            sb.Append("  StartPositionTicks: ").Append(StartPositionTicks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlayRequestDto);
        }

        /// <summary>
        /// Returns true if PlayRequestDto instances are equal
        /// </summary>
        /// <param name="input">Instance of PlayRequestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlayRequestDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlayingQueue == input.PlayingQueue ||
                    this.PlayingQueue != null &&
                    input.PlayingQueue != null &&
                    this.PlayingQueue.SequenceEqual(input.PlayingQueue)
                ) && 
                (
                    this.PlayingItemPosition == input.PlayingItemPosition ||
                    (this.PlayingItemPosition != null &&
                    this.PlayingItemPosition.Equals(input.PlayingItemPosition))
                ) && 
                (
                    this.StartPositionTicks == input.StartPositionTicks ||
                    (this.StartPositionTicks != null &&
                    this.StartPositionTicks.Equals(input.StartPositionTicks))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlayingQueue != null)
                    hashCode = hashCode * 59 + this.PlayingQueue.GetHashCode();
                if (this.PlayingItemPosition != null)
                    hashCode = hashCode * 59 + this.PlayingItemPosition.GetHashCode();
                if (this.StartPositionTicks != null)
                    hashCode = hashCode * 59 + this.StartPositionTicks.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
