/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Jellyfin.Api.Client;
using Jellyfin.Api.Model;

namespace Jellyfin.Api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISearchApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets the search hint result.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <returns>SearchHintResult</returns>
        SearchHintResult Get (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?));

        /// <summary>
        /// Gets the search hint result.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <returns>ApiResponse of SearchHintResult</returns>
        ApiResponse<SearchHintResult> GetWithHttpInfo (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Gets the search hint result.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SearchHintResult</returns>
        System.Threading.Tasks.Task<SearchHintResult> GetAsync (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Gets the search hint result.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SearchHintResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SearchHintResult>> GetWithHttpInfoAsync (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SearchApi : ISearchApi
    {
        private Jellyfin.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SearchApi(String basePath)
        {
            this.Configuration = new Jellyfin.Api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Jellyfin.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// </summary>
        /// <returns></returns>
        public SearchApi()
        {
            this.Configuration = Jellyfin.Api.Client.Configuration.Default;

            ExceptionFactory = Jellyfin.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SearchApi(Jellyfin.Api.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Jellyfin.Api.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Jellyfin.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Jellyfin.Api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Jellyfin.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Gets the search hint result. 
        /// </summary>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <returns>SearchHintResult</returns>
        public SearchHintResult Get (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?))
        {
             ApiResponse<SearchHintResult> localVarResponse = GetWithHttpInfo(searchTerm, startIndex, limit, userId, includeItemTypes, excludeItemTypes, mediaTypes, parentId, isMovie, isSeries, isNews, isKids, isSports, includePeople, includeMedia, includeGenres, includeStudios, includeArtists);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the search hint result. 
        /// </summary>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <returns>ApiResponse of SearchHintResult</returns>
        public ApiResponse<SearchHintResult> GetWithHttpInfo (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?))
        {
            // verify the required parameter 'searchTerm' is set
            if (searchTerm == null)
                throw new ApiException(400, "Missing required parameter 'searchTerm' when calling SearchApi->Get");

            var localVarPath = "/Search/Hints";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/json; profile=CamelCase",
                "application/json; profile=PascalCase"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startIndex != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "startIndex", startIndex)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (includeItemTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "includeItemTypes", includeItemTypes)); // query parameter
            if (excludeItemTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "excludeItemTypes", excludeItemTypes)); // query parameter
            if (mediaTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "mediaTypes", mediaTypes)); // query parameter
            if (parentId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "parentId", parentId)); // query parameter
            if (isMovie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isMovie", isMovie)); // query parameter
            if (isSeries != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isSeries", isSeries)); // query parameter
            if (isNews != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isNews", isNews)); // query parameter
            if (isKids != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isKids", isKids)); // query parameter
            if (isSports != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isSports", isSports)); // query parameter
            if (includePeople != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includePeople", includePeople)); // query parameter
            if (includeMedia != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeMedia", includeMedia)); // query parameter
            if (includeGenres != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeGenres", includeGenres)); // query parameter
            if (includeStudios != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeStudios", includeStudios)); // query parameter
            if (includeArtists != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeArtists", includeArtists)); // query parameter

            // authentication (CustomAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Emby-Authorization")))
            {
                localVarHeaderParams["X-Emby-Authorization"] = this.Configuration.GetApiKeyWithPrefix("X-Emby-Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SearchHintResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SearchHintResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SearchHintResult)));
        }

        /// <summary>
        /// Gets the search hint result. 
        /// </summary>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of SearchHintResult</returns>
        public async System.Threading.Tasks.Task<SearchHintResult> GetAsync (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<SearchHintResult> localVarResponse = await GetWithHttpInfoAsync(searchTerm, startIndex, limit, userId, includeItemTypes, excludeItemTypes, mediaTypes, parentId, isMovie, isSeries, isNews, isKids, isSports, includePeople, includeMedia, includeGenres, includeStudios, includeArtists, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the search hint result. 
        /// </summary>
        /// <exception cref="Jellyfin.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchTerm">The search term to filter on.</param>
        /// <param name="startIndex">Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)</param>
        /// <param name="limit">Optional. The maximum number of records to return. (optional)</param>
        /// <param name="userId">Optional. Supply a user id to search within a user&#39;s library or omit to search all. (optional)</param>
        /// <param name="includeItemTypes">If specified, only results with the specified item types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="excludeItemTypes">If specified, results with these item types are filtered out. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="mediaTypes">If specified, only results with the specified media types are returned. This allows multiple, comma delimeted. (optional)</param>
        /// <param name="parentId">If specified, only children of the parent are returned. (optional)</param>
        /// <param name="isMovie">Optional filter for movies. (optional)</param>
        /// <param name="isSeries">Optional filter for series. (optional)</param>
        /// <param name="isNews">Optional filter for news. (optional)</param>
        /// <param name="isKids">Optional filter for kids. (optional)</param>
        /// <param name="isSports">Optional filter for sports. (optional)</param>
        /// <param name="includePeople">Optional filter whether to include people. (optional, default to true)</param>
        /// <param name="includeMedia">Optional filter whether to include media. (optional, default to true)</param>
        /// <param name="includeGenres">Optional filter whether to include genres. (optional, default to true)</param>
        /// <param name="includeStudios">Optional filter whether to include studios. (optional, default to true)</param>
        /// <param name="includeArtists">Optional filter whether to include artists. (optional, default to true)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (SearchHintResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SearchHintResult>> GetWithHttpInfoAsync (string searchTerm, int? startIndex = default(int?), int? limit = default(int?), Guid? userId = default(Guid?), List<string> includeItemTypes = default(List<string>), List<string> excludeItemTypes = default(List<string>), List<string> mediaTypes = default(List<string>), Guid? parentId = default(Guid?), bool? isMovie = default(bool?), bool? isSeries = default(bool?), bool? isNews = default(bool?), bool? isKids = default(bool?), bool? isSports = default(bool?), bool? includePeople = default(bool?), bool? includeMedia = default(bool?), bool? includeGenres = default(bool?), bool? includeStudios = default(bool?), bool? includeArtists = default(bool?), CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'searchTerm' is set
            if (searchTerm == null)
                throw new ApiException(400, "Missing required parameter 'searchTerm' when calling SearchApi->Get");

            var localVarPath = "/Search/Hints";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/json; profile=CamelCase",
                "application/json; profile=PascalCase"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startIndex != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "startIndex", startIndex)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter
            if (userId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "userId", userId)); // query parameter
            if (searchTerm != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "searchTerm", searchTerm)); // query parameter
            if (includeItemTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "includeItemTypes", includeItemTypes)); // query parameter
            if (excludeItemTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "excludeItemTypes", excludeItemTypes)); // query parameter
            if (mediaTypes != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("multi", "mediaTypes", mediaTypes)); // query parameter
            if (parentId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "parentId", parentId)); // query parameter
            if (isMovie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isMovie", isMovie)); // query parameter
            if (isSeries != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isSeries", isSeries)); // query parameter
            if (isNews != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isNews", isNews)); // query parameter
            if (isKids != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isKids", isKids)); // query parameter
            if (isSports != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "isSports", isSports)); // query parameter
            if (includePeople != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includePeople", includePeople)); // query parameter
            if (includeMedia != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeMedia", includeMedia)); // query parameter
            if (includeGenres != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeGenres", includeGenres)); // query parameter
            if (includeStudios != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeStudios", includeStudios)); // query parameter
            if (includeArtists != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "includeArtists", includeArtists)); // query parameter

            // authentication (CustomAuthentication) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-Emby-Authorization")))
            {
                localVarHeaderParams["X-Emby-Authorization"] = this.Configuration.GetApiKeyWithPrefix("X-Emby-Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Get", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SearchHintResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SearchHintResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SearchHintResult)));
        }

    }
}
