/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing ChannelFeatures
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChannelFeaturesTests
    {
        // TODO uncomment below to declare an instance variable for ChannelFeatures
        //private ChannelFeatures instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChannelFeatures
            //instance = new ChannelFeatures();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChannelFeatures
        /// </summary>
        [Test]
        public void ChannelFeaturesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ChannelFeatures
            //Assert.IsInstanceOf(typeof(ChannelFeatures), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CanSearch'
        /// </summary>
        [Test]
        public void CanSearchTest()
        {
            // TODO unit test for the property 'CanSearch'
        }
        /// <summary>
        /// Test the property 'MediaTypes'
        /// </summary>
        [Test]
        public void MediaTypesTest()
        {
            // TODO unit test for the property 'MediaTypes'
        }
        /// <summary>
        /// Test the property 'ContentTypes'
        /// </summary>
        [Test]
        public void ContentTypesTest()
        {
            // TODO unit test for the property 'ContentTypes'
        }
        /// <summary>
        /// Test the property 'MaxPageSize'
        /// </summary>
        [Test]
        public void MaxPageSizeTest()
        {
            // TODO unit test for the property 'MaxPageSize'
        }
        /// <summary>
        /// Test the property 'AutoRefreshLevels'
        /// </summary>
        [Test]
        public void AutoRefreshLevelsTest()
        {
            // TODO unit test for the property 'AutoRefreshLevels'
        }
        /// <summary>
        /// Test the property 'DefaultSortFields'
        /// </summary>
        [Test]
        public void DefaultSortFieldsTest()
        {
            // TODO unit test for the property 'DefaultSortFields'
        }
        /// <summary>
        /// Test the property 'SupportsSortOrderToggle'
        /// </summary>
        [Test]
        public void SupportsSortOrderToggleTest()
        {
            // TODO unit test for the property 'SupportsSortOrderToggle'
        }
        /// <summary>
        /// Test the property 'SupportsLatestMedia'
        /// </summary>
        [Test]
        public void SupportsLatestMediaTest()
        {
            // TODO unit test for the property 'SupportsLatestMedia'
        }
        /// <summary>
        /// Test the property 'CanFilter'
        /// </summary>
        [Test]
        public void CanFilterTest()
        {
            // TODO unit test for the property 'CanFilter'
        }
        /// <summary>
        /// Test the property 'SupportsContentDownloading'
        /// </summary>
        [Test]
        public void SupportsContentDownloadingTest()
        {
            // TODO unit test for the property 'SupportsContentDownloading'
        }

    }

}
