/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing ChapterInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChapterInfoTests
    {
        // TODO uncomment below to declare an instance variable for ChapterInfo
        //private ChapterInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChapterInfo
            //instance = new ChapterInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChapterInfo
        /// </summary>
        [Test]
        public void ChapterInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ChapterInfo
            //Assert.IsInstanceOf(typeof(ChapterInfo), instance);
        }


        /// <summary>
        /// Test the property 'StartPositionTicks'
        /// </summary>
        [Test]
        public void StartPositionTicksTest()
        {
            // TODO unit test for the property 'StartPositionTicks'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ImagePath'
        /// </summary>
        [Test]
        public void ImagePathTest()
        {
            // TODO unit test for the property 'ImagePath'
        }
        /// <summary>
        /// Test the property 'ImageDateModified'
        /// </summary>
        [Test]
        public void ImageDateModifiedTest()
        {
            // TODO unit test for the property 'ImageDateModified'
        }
        /// <summary>
        /// Test the property 'ImageTag'
        /// </summary>
        [Test]
        public void ImageTagTest()
        {
            // TODO unit test for the property 'ImageTag'
        }

    }

}
