/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing CodecProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CodecProfileTests
    {
        // TODO uncomment below to declare an instance variable for CodecProfile
        //private CodecProfile instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CodecProfile
            //instance = new CodecProfile();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CodecProfile
        /// </summary>
        [Test]
        public void CodecProfileInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CodecProfile
            //Assert.IsInstanceOf(typeof(CodecProfile), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }
        /// <summary>
        /// Test the property 'ApplyConditions'
        /// </summary>
        [Test]
        public void ApplyConditionsTest()
        {
            // TODO unit test for the property 'ApplyConditions'
        }
        /// <summary>
        /// Test the property 'Codec'
        /// </summary>
        [Test]
        public void CodecTest()
        {
            // TODO unit test for the property 'Codec'
        }
        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }

    }

}
