/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing DeviceIdentification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceIdentificationTests
    {
        // TODO uncomment below to declare an instance variable for DeviceIdentification
        //private DeviceIdentification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceIdentification
            //instance = new DeviceIdentification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceIdentification
        /// </summary>
        [Test]
        public void DeviceIdentificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DeviceIdentification
            //Assert.IsInstanceOf(typeof(DeviceIdentification), instance);
        }


        /// <summary>
        /// Test the property 'FriendlyName'
        /// </summary>
        [Test]
        public void FriendlyNameTest()
        {
            // TODO unit test for the property 'FriendlyName'
        }
        /// <summary>
        /// Test the property 'ModelNumber'
        /// </summary>
        [Test]
        public void ModelNumberTest()
        {
            // TODO unit test for the property 'ModelNumber'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'ModelName'
        /// </summary>
        [Test]
        public void ModelNameTest()
        {
            // TODO unit test for the property 'ModelName'
        }
        /// <summary>
        /// Test the property 'ModelDescription'
        /// </summary>
        [Test]
        public void ModelDescriptionTest()
        {
            // TODO unit test for the property 'ModelDescription'
        }
        /// <summary>
        /// Test the property 'ModelUrl'
        /// </summary>
        [Test]
        public void ModelUrlTest()
        {
            // TODO unit test for the property 'ModelUrl'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'ManufacturerUrl'
        /// </summary>
        [Test]
        public void ManufacturerUrlTest()
        {
            // TODO unit test for the property 'ManufacturerUrl'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

    }

}
