/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing EndPointInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EndPointInfoTests
    {
        // TODO uncomment below to declare an instance variable for EndPointInfo
        //private EndPointInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EndPointInfo
            //instance = new EndPointInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EndPointInfo
        /// </summary>
        [Test]
        public void EndPointInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EndPointInfo
            //Assert.IsInstanceOf(typeof(EndPointInfo), instance);
        }


        /// <summary>
        /// Test the property 'IsLocal'
        /// </summary>
        [Test]
        public void IsLocalTest()
        {
            // TODO unit test for the property 'IsLocal'
        }
        /// <summary>
        /// Test the property 'IsInNetwork'
        /// </summary>
        [Test]
        public void IsInNetworkTest()
        {
            // TODO unit test for the property 'IsInNetwork'
        }

    }

}
