/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing IPlugin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IPluginTests
    {
        // TODO uncomment below to declare an instance variable for IPlugin
        //private IPlugin instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IPlugin
            //instance = new IPlugin();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IPlugin
        /// </summary>
        [Test]
        public void IPluginInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" IPlugin
            //Assert.IsInstanceOf(typeof(IPlugin), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'AssemblyFilePath'
        /// </summary>
        [Test]
        public void AssemblyFilePathTest()
        {
            // TODO unit test for the property 'AssemblyFilePath'
        }
        /// <summary>
        /// Test the property 'CanUninstall'
        /// </summary>
        [Test]
        public void CanUninstallTest()
        {
            // TODO unit test for the property 'CanUninstall'
        }
        /// <summary>
        /// Test the property 'DataFolderPath'
        /// </summary>
        [Test]
        public void DataFolderPathTest()
        {
            // TODO unit test for the property 'DataFolderPath'
        }

    }

}
