/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing MediaSourceInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaSourceInfoTests
    {
        // TODO uncomment below to declare an instance variable for MediaSourceInfo
        //private MediaSourceInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaSourceInfo
            //instance = new MediaSourceInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaSourceInfo
        /// </summary>
        [Test]
        public void MediaSourceInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MediaSourceInfo
            //Assert.IsInstanceOf(typeof(MediaSourceInfo), instance);
        }


        /// <summary>
        /// Test the property 'Protocol'
        /// </summary>
        [Test]
        public void ProtocolTest()
        {
            // TODO unit test for the property 'Protocol'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'EncoderPath'
        /// </summary>
        [Test]
        public void EncoderPathTest()
        {
            // TODO unit test for the property 'EncoderPath'
        }
        /// <summary>
        /// Test the property 'EncoderProtocol'
        /// </summary>
        [Test]
        public void EncoderProtocolTest()
        {
            // TODO unit test for the property 'EncoderProtocol'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsRemote'
        /// </summary>
        [Test]
        public void IsRemoteTest()
        {
            // TODO unit test for the property 'IsRemote'
        }
        /// <summary>
        /// Test the property 'ETag'
        /// </summary>
        [Test]
        public void ETagTest()
        {
            // TODO unit test for the property 'ETag'
        }
        /// <summary>
        /// Test the property 'RunTimeTicks'
        /// </summary>
        [Test]
        public void RunTimeTicksTest()
        {
            // TODO unit test for the property 'RunTimeTicks'
        }
        /// <summary>
        /// Test the property 'ReadAtNativeFramerate'
        /// </summary>
        [Test]
        public void ReadAtNativeFramerateTest()
        {
            // TODO unit test for the property 'ReadAtNativeFramerate'
        }
        /// <summary>
        /// Test the property 'IgnoreDts'
        /// </summary>
        [Test]
        public void IgnoreDtsTest()
        {
            // TODO unit test for the property 'IgnoreDts'
        }
        /// <summary>
        /// Test the property 'IgnoreIndex'
        /// </summary>
        [Test]
        public void IgnoreIndexTest()
        {
            // TODO unit test for the property 'IgnoreIndex'
        }
        /// <summary>
        /// Test the property 'GenPtsInput'
        /// </summary>
        [Test]
        public void GenPtsInputTest()
        {
            // TODO unit test for the property 'GenPtsInput'
        }
        /// <summary>
        /// Test the property 'SupportsTranscoding'
        /// </summary>
        [Test]
        public void SupportsTranscodingTest()
        {
            // TODO unit test for the property 'SupportsTranscoding'
        }
        /// <summary>
        /// Test the property 'SupportsDirectStream'
        /// </summary>
        [Test]
        public void SupportsDirectStreamTest()
        {
            // TODO unit test for the property 'SupportsDirectStream'
        }
        /// <summary>
        /// Test the property 'SupportsDirectPlay'
        /// </summary>
        [Test]
        public void SupportsDirectPlayTest()
        {
            // TODO unit test for the property 'SupportsDirectPlay'
        }
        /// <summary>
        /// Test the property 'IsInfiniteStream'
        /// </summary>
        [Test]
        public void IsInfiniteStreamTest()
        {
            // TODO unit test for the property 'IsInfiniteStream'
        }
        /// <summary>
        /// Test the property 'RequiresOpening'
        /// </summary>
        [Test]
        public void RequiresOpeningTest()
        {
            // TODO unit test for the property 'RequiresOpening'
        }
        /// <summary>
        /// Test the property 'OpenToken'
        /// </summary>
        [Test]
        public void OpenTokenTest()
        {
            // TODO unit test for the property 'OpenToken'
        }
        /// <summary>
        /// Test the property 'RequiresClosing'
        /// </summary>
        [Test]
        public void RequiresClosingTest()
        {
            // TODO unit test for the property 'RequiresClosing'
        }
        /// <summary>
        /// Test the property 'LiveStreamId'
        /// </summary>
        [Test]
        public void LiveStreamIdTest()
        {
            // TODO unit test for the property 'LiveStreamId'
        }
        /// <summary>
        /// Test the property 'BufferMs'
        /// </summary>
        [Test]
        public void BufferMsTest()
        {
            // TODO unit test for the property 'BufferMs'
        }
        /// <summary>
        /// Test the property 'RequiresLooping'
        /// </summary>
        [Test]
        public void RequiresLoopingTest()
        {
            // TODO unit test for the property 'RequiresLooping'
        }
        /// <summary>
        /// Test the property 'SupportsProbing'
        /// </summary>
        [Test]
        public void SupportsProbingTest()
        {
            // TODO unit test for the property 'SupportsProbing'
        }
        /// <summary>
        /// Test the property 'VideoType'
        /// </summary>
        [Test]
        public void VideoTypeTest()
        {
            // TODO unit test for the property 'VideoType'
        }
        /// <summary>
        /// Test the property 'IsoType'
        /// </summary>
        [Test]
        public void IsoTypeTest()
        {
            // TODO unit test for the property 'IsoType'
        }
        /// <summary>
        /// Test the property 'Video3DFormat'
        /// </summary>
        [Test]
        public void Video3DFormatTest()
        {
            // TODO unit test for the property 'Video3DFormat'
        }
        /// <summary>
        /// Test the property 'MediaStreams'
        /// </summary>
        [Test]
        public void MediaStreamsTest()
        {
            // TODO unit test for the property 'MediaStreams'
        }
        /// <summary>
        /// Test the property 'MediaAttachments'
        /// </summary>
        [Test]
        public void MediaAttachmentsTest()
        {
            // TODO unit test for the property 'MediaAttachments'
        }
        /// <summary>
        /// Test the property 'Formats'
        /// </summary>
        [Test]
        public void FormatsTest()
        {
            // TODO unit test for the property 'Formats'
        }
        /// <summary>
        /// Test the property 'Bitrate'
        /// </summary>
        [Test]
        public void BitrateTest()
        {
            // TODO unit test for the property 'Bitrate'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'RequiredHttpHeaders'
        /// </summary>
        [Test]
        public void RequiredHttpHeadersTest()
        {
            // TODO unit test for the property 'RequiredHttpHeaders'
        }
        /// <summary>
        /// Test the property 'TranscodingUrl'
        /// </summary>
        [Test]
        public void TranscodingUrlTest()
        {
            // TODO unit test for the property 'TranscodingUrl'
        }
        /// <summary>
        /// Test the property 'TranscodingSubProtocol'
        /// </summary>
        [Test]
        public void TranscodingSubProtocolTest()
        {
            // TODO unit test for the property 'TranscodingSubProtocol'
        }
        /// <summary>
        /// Test the property 'TranscodingContainer'
        /// </summary>
        [Test]
        public void TranscodingContainerTest()
        {
            // TODO unit test for the property 'TranscodingContainer'
        }
        /// <summary>
        /// Test the property 'AnalyzeDurationMs'
        /// </summary>
        [Test]
        public void AnalyzeDurationMsTest()
        {
            // TODO unit test for the property 'AnalyzeDurationMs'
        }
        /// <summary>
        /// Test the property 'DefaultAudioStreamIndex'
        /// </summary>
        [Test]
        public void DefaultAudioStreamIndexTest()
        {
            // TODO unit test for the property 'DefaultAudioStreamIndex'
        }
        /// <summary>
        /// Test the property 'DefaultSubtitleStreamIndex'
        /// </summary>
        [Test]
        public void DefaultSubtitleStreamIndexTest()
        {
            // TODO unit test for the property 'DefaultSubtitleStreamIndex'
        }

    }

}
