/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing MediaEncoderPathDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaEncoderPathDtoTests
    {
        // TODO uncomment below to declare an instance variable for MediaEncoderPathDto
        //private MediaEncoderPathDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaEncoderPathDto
            //instance = new MediaEncoderPathDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaEncoderPathDto
        /// </summary>
        [Test]
        public void MediaEncoderPathDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MediaEncoderPathDto
            //Assert.IsInstanceOf(typeof(MediaEncoderPathDto), instance);
        }


        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'PathType'
        /// </summary>
        [Test]
        public void PathTypeTest()
        {
            // TODO unit test for the property 'PathType'
        }

    }

}
