/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing MediaUpdateInfoDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MediaUpdateInfoDtoTests
    {
        // TODO uncomment below to declare an instance variable for MediaUpdateInfoDto
        //private MediaUpdateInfoDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MediaUpdateInfoDto
            //instance = new MediaUpdateInfoDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MediaUpdateInfoDto
        /// </summary>
        [Test]
        public void MediaUpdateInfoDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MediaUpdateInfoDto
            //Assert.IsInstanceOf(typeof(MediaUpdateInfoDto), instance);
        }


        /// <summary>
        /// Test the property 'Updates'
        /// </summary>
        [Test]
        public void UpdatesTest()
        {
            // TODO unit test for the property 'Updates'
        }

    }

}
