/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing NotificationsSummaryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationsSummaryDtoTests
    {
        // TODO uncomment below to declare an instance variable for NotificationsSummaryDto
        //private NotificationsSummaryDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationsSummaryDto
            //instance = new NotificationsSummaryDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationsSummaryDto
        /// </summary>
        [Test]
        public void NotificationsSummaryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NotificationsSummaryDto
            //Assert.IsInstanceOf(typeof(NotificationsSummaryDto), instance);
        }


        /// <summary>
        /// Test the property 'UnreadCount'
        /// </summary>
        [Test]
        public void UnreadCountTest()
        {
            // TODO unit test for the property 'UnreadCount'
        }
        /// <summary>
        /// Test the property 'MaxUnreadNotificationLevel'
        /// </summary>
        [Test]
        public void MaxUnreadNotificationLevelTest()
        {
            // TODO unit test for the property 'MaxUnreadNotificationLevel'
        }

    }

}
