/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing PlaybackInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlaybackInfoResponseTests
    {
        // TODO uncomment below to declare an instance variable for PlaybackInfoResponse
        //private PlaybackInfoResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlaybackInfoResponse
            //instance = new PlaybackInfoResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlaybackInfoResponse
        /// </summary>
        [Test]
        public void PlaybackInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PlaybackInfoResponse
            //Assert.IsInstanceOf(typeof(PlaybackInfoResponse), instance);
        }


        /// <summary>
        /// Test the property 'MediaSources'
        /// </summary>
        [Test]
        public void MediaSourcesTest()
        {
            // TODO unit test for the property 'MediaSources'
        }
        /// <summary>
        /// Test the property 'PlaySessionId'
        /// </summary>
        [Test]
        public void PlaySessionIdTest()
        {
            // TODO unit test for the property 'PlaySessionId'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

    }

}
