/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing PublicSystemInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicSystemInfoTests
    {
        // TODO uncomment below to declare an instance variable for PublicSystemInfo
        //private PublicSystemInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PublicSystemInfo
            //instance = new PublicSystemInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PublicSystemInfo
        /// </summary>
        [Test]
        public void PublicSystemInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PublicSystemInfo
            //Assert.IsInstanceOf(typeof(PublicSystemInfo), instance);
        }


        /// <summary>
        /// Test the property 'LocalAddress'
        /// </summary>
        [Test]
        public void LocalAddressTest()
        {
            // TODO unit test for the property 'LocalAddress'
        }
        /// <summary>
        /// Test the property 'ServerName'
        /// </summary>
        [Test]
        public void ServerNameTest()
        {
            // TODO unit test for the property 'ServerName'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'OperatingSystem'
        /// </summary>
        [Test]
        public void OperatingSystemTest()
        {
            // TODO unit test for the property 'OperatingSystem'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'StartupWizardCompleted'
        /// </summary>
        [Test]
        public void StartupWizardCompletedTest()
        {
            // TODO unit test for the property 'StartupWizardCompleted'
        }

    }

}
