/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing RemoteSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemoteSearchResultTests
    {
        // TODO uncomment below to declare an instance variable for RemoteSearchResult
        //private RemoteSearchResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RemoteSearchResult
            //instance = new RemoteSearchResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RemoteSearchResult
        /// </summary>
        [Test]
        public void RemoteSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RemoteSearchResult
            //Assert.IsInstanceOf(typeof(RemoteSearchResult), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProviderIds'
        /// </summary>
        [Test]
        public void ProviderIdsTest()
        {
            // TODO unit test for the property 'ProviderIds'
        }
        /// <summary>
        /// Test the property 'ProductionYear'
        /// </summary>
        [Test]
        public void ProductionYearTest()
        {
            // TODO unit test for the property 'ProductionYear'
        }
        /// <summary>
        /// Test the property 'IndexNumber'
        /// </summary>
        [Test]
        public void IndexNumberTest()
        {
            // TODO unit test for the property 'IndexNumber'
        }
        /// <summary>
        /// Test the property 'IndexNumberEnd'
        /// </summary>
        [Test]
        public void IndexNumberEndTest()
        {
            // TODO unit test for the property 'IndexNumberEnd'
        }
        /// <summary>
        /// Test the property 'ParentIndexNumber'
        /// </summary>
        [Test]
        public void ParentIndexNumberTest()
        {
            // TODO unit test for the property 'ParentIndexNumber'
        }
        /// <summary>
        /// Test the property 'PremiereDate'
        /// </summary>
        [Test]
        public void PremiereDateTest()
        {
            // TODO unit test for the property 'PremiereDate'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Test]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'SearchProviderName'
        /// </summary>
        [Test]
        public void SearchProviderNameTest()
        {
            // TODO unit test for the property 'SearchProviderName'
        }
        /// <summary>
        /// Test the property 'Overview'
        /// </summary>
        [Test]
        public void OverviewTest()
        {
            // TODO unit test for the property 'Overview'
        }
        /// <summary>
        /// Test the property 'AlbumArtist'
        /// </summary>
        [Test]
        public void AlbumArtistTest()
        {
            // TODO unit test for the property 'AlbumArtist'
        }
        /// <summary>
        /// Test the property 'Artists'
        /// </summary>
        [Test]
        public void ArtistsTest()
        {
            // TODO unit test for the property 'Artists'
        }

    }

}
