/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing TaskTriggerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskTriggerInfoTests
    {
        // TODO uncomment below to declare an instance variable for TaskTriggerInfo
        //private TaskTriggerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TaskTriggerInfo
            //instance = new TaskTriggerInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskTriggerInfo
        /// </summary>
        [Test]
        public void TaskTriggerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TaskTriggerInfo
            //Assert.IsInstanceOf(typeof(TaskTriggerInfo), instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TimeOfDayTicks'
        /// </summary>
        [Test]
        public void TimeOfDayTicksTest()
        {
            // TODO unit test for the property 'TimeOfDayTicks'
        }
        /// <summary>
        /// Test the property 'IntervalTicks'
        /// </summary>
        [Test]
        public void IntervalTicksTest()
        {
            // TODO unit test for the property 'IntervalTicks'
        }
        /// <summary>
        /// Test the property 'DayOfWeek'
        /// </summary>
        [Test]
        public void DayOfWeekTest()
        {
            // TODO unit test for the property 'DayOfWeek'
        }
        /// <summary>
        /// Test the property 'MaxRuntimeTicks'
        /// </summary>
        [Test]
        public void MaxRuntimeTicksTest()
        {
            // TODO unit test for the property 'MaxRuntimeTicks'
        }

    }

}
