/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing TunerChannelMapping
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TunerChannelMappingTests
    {
        // TODO uncomment below to declare an instance variable for TunerChannelMapping
        //private TunerChannelMapping instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TunerChannelMapping
            //instance = new TunerChannelMapping();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TunerChannelMapping
        /// </summary>
        [Test]
        public void TunerChannelMappingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TunerChannelMapping
            //Assert.IsInstanceOf(typeof(TunerChannelMapping), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProviderChannelName'
        /// </summary>
        [Test]
        public void ProviderChannelNameTest()
        {
            // TODO unit test for the property 'ProviderChannelName'
        }
        /// <summary>
        /// Test the property 'ProviderChannelId'
        /// </summary>
        [Test]
        public void ProviderChannelIdTest()
        {
            // TODO unit test for the property 'ProviderChannelId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
