/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;
using Jellyfin.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing UpdateUserEasyPassword
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateUserEasyPasswordTests
    {
        // TODO uncomment below to declare an instance variable for UpdateUserEasyPassword
        //private UpdateUserEasyPassword instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateUserEasyPassword
            //instance = new UpdateUserEasyPassword();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateUserEasyPassword
        /// </summary>
        [Test]
        public void UpdateUserEasyPasswordInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateUserEasyPassword
            //Assert.IsInstanceOf(typeof(UpdateUserEasyPassword), instance);
        }


        /// <summary>
        /// Test the property 'NewPassword'
        /// </summary>
        [Test]
        public void NewPasswordTest()
        {
            // TODO unit test for the property 'NewPassword'
        }
        /// <summary>
        /// Test the property 'NewPw'
        /// </summary>
        [Test]
        public void NewPwTest()
        {
            // TODO unit test for the property 'NewPw'
        }
        /// <summary>
        /// Test the property 'ResetPassword'
        /// </summary>
        [Test]
        public void ResetPasswordTest()
        {
            // TODO unit test for the property 'ResetPassword'
        }

    }

}
