/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Jellyfin.Api.Client;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing DashboardApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DashboardApiTests
    {
        private DashboardApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DashboardApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DashboardApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DashboardApi
            //Assert.IsInstanceOf(typeof(DashboardApi), instance);
        }

        
        /// <summary>
        /// Test GetConfigurationPages
        /// </summary>
        [Test]
        public void GetConfigurationPagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? enableInMainMenu = null;
            //ConfigurationPageType? pageType = null;
            //var response = instance.GetConfigurationPages(enableInMainMenu, pageType);
            //Assert.IsInstanceOf(typeof(List<ConfigurationPageInfo>), response, "response is List<ConfigurationPageInfo>");
        }
        
        /// <summary>
        /// Test GetDashboardConfigurationPage
        /// </summary>
        [Test]
        public void GetDashboardConfigurationPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.GetDashboardConfigurationPage(name);
            //Assert.IsInstanceOf(typeof(System.IO.Stream), response, "response is System.IO.Stream");
        }
        
    }

}
