/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Jellyfin.Api.Client;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing ItemLookupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ItemLookupApiTests
    {
        private ItemLookupApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ItemLookupApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemLookupApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ItemLookupApi
            //Assert.IsInstanceOf(typeof(ItemLookupApi), instance);
        }

        
        /// <summary>
        /// Test ApplySearchCriteria
        /// </summary>
        [Test]
        public void ApplySearchCriteriaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid itemId = null;
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //bool? replaceAllImages = null;
            //instance.ApplySearchCriteria(itemId, UNKNOWN_BASE_TYPE, replaceAllImages);
            
        }
        
        /// <summary>
        /// Test GetBookRemoteSearchResults
        /// </summary>
        [Test]
        public void GetBookRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetBookRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetBoxSetRemoteSearchResults
        /// </summary>
        [Test]
        public void GetBoxSetRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetBoxSetRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetExternalIdInfos
        /// </summary>
        [Test]
        public void GetExternalIdInfosTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid itemId = null;
            //var response = instance.GetExternalIdInfos(itemId);
            //Assert.IsInstanceOf(typeof(List<ExternalIdInfo>), response, "response is List<ExternalIdInfo>");
        }
        
        /// <summary>
        /// Test GetMovieRemoteSearchResults
        /// </summary>
        [Test]
        public void GetMovieRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetMovieRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetMusicAlbumRemoteSearchResults
        /// </summary>
        [Test]
        public void GetMusicAlbumRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetMusicAlbumRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetMusicArtistRemoteSearchResults
        /// </summary>
        [Test]
        public void GetMusicArtistRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetMusicArtistRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetMusicVideoRemoteSearchResults
        /// </summary>
        [Test]
        public void GetMusicVideoRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetMusicVideoRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetPersonRemoteSearchResults
        /// </summary>
        [Test]
        public void GetPersonRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetPersonRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetSeriesRemoteSearchResults
        /// </summary>
        [Test]
        public void GetSeriesRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetSeriesRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
        /// <summary>
        /// Test GetTrailerRemoteSearchResults
        /// </summary>
        [Test]
        public void GetTrailerRemoteSearchResultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
            //var response = instance.GetTrailerRemoteSearchResults(UNKNOWN_BASE_TYPE);
            //Assert.IsInstanceOf(typeof(List<RemoteSearchResult>), response, "response is List<RemoteSearchResult>");
        }
        
    }

}
