/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Jellyfin.Api.Client;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing PersonsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PersonsApiTests
    {
        private PersonsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PersonsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PersonsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' PersonsApi
            //Assert.IsInstanceOf(typeof(PersonsApi), instance);
        }

        
        /// <summary>
        /// Test GetPerson
        /// </summary>
        [Test]
        public void GetPersonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //Guid? userId = null;
            //var response = instance.GetPerson(name, userId);
            //Assert.IsInstanceOf(typeof(BaseItemDto), response, "response is BaseItemDto");
        }
        
        /// <summary>
        /// Test GetPersons
        /// </summary>
        [Test]
        public void GetPersonsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string searchTerm = null;
            //List<ItemFields> fields = null;
            //List<ItemFilter> filters = null;
            //bool? isFavorite = null;
            //bool? enableUserData = null;
            //int? imageTypeLimit = null;
            //List<ImageType> enableImageTypes = null;
            //List<string> excludePersonTypes = null;
            //List<string> personTypes = null;
            //Guid? appearsInItemId = null;
            //Guid? userId = null;
            //bool? enableImages = null;
            //var response = instance.GetPersons(limit, searchTerm, fields, filters, isFavorite, enableUserData, imageTypeLimit, enableImageTypes, excludePersonTypes, personTypes, appearsInItemId, userId, enableImages);
            //Assert.IsInstanceOf(typeof(BaseItemDtoQueryResult), response, "response is BaseItemDtoQueryResult");
        }
        
    }

}
