/*
 * Jellyfin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 10.7.6
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Jellyfin.Api.Client;
using Jellyfin.Api.Api;
using Jellyfin.Api.Model;

namespace Jellyfin.Api.Test
{
    /// <summary>
    ///  Class for testing StudiosApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StudiosApiTests
    {
        private StudiosApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new StudiosApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StudiosApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' StudiosApi
            //Assert.IsInstanceOf(typeof(StudiosApi), instance);
        }

        
        /// <summary>
        /// Test GetStudio
        /// </summary>
        [Test]
        public void GetStudioTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //Guid? userId = null;
            //var response = instance.GetStudio(name, userId);
            //Assert.IsInstanceOf(typeof(BaseItemDto), response, "response is BaseItemDto");
        }
        
        /// <summary>
        /// Test GetStudios
        /// </summary>
        [Test]
        public void GetStudiosTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? startIndex = null;
            //int? limit = null;
            //string searchTerm = null;
            //Guid? parentId = null;
            //List<ItemFields> fields = null;
            //List<string> excludeItemTypes = null;
            //List<string> includeItemTypes = null;
            //bool? isFavorite = null;
            //bool? enableUserData = null;
            //int? imageTypeLimit = null;
            //List<ImageType> enableImageTypes = null;
            //Guid? userId = null;
            //string nameStartsWithOrGreater = null;
            //string nameStartsWith = null;
            //string nameLessThan = null;
            //bool? enableImages = null;
            //bool? enableTotalRecordCount = null;
            //var response = instance.GetStudios(startIndex, limit, searchTerm, parentId, fields, excludeItemTypes, includeItemTypes, isFavorite, enableUserData, imageTypeLimit, enableImageTypes, userId, nameStartsWithOrGreater, nameStartsWith, nameLessThan, enableImages, enableTotalRecordCount);
            //Assert.IsInstanceOf(typeof(BaseItemDtoQueryResult), response, "response is BaseItemDtoQueryResult");
        }
        
    }

}
